from __future__ import annotations

"""Interactive, reusable chart infrastructure for Omega FISH.

The module deliberately keeps chart generation separate from Tkinter so the same
figures can be opened from the desktop application, generated by the CLI, used in
reports, or exercised in automated tests. Plotly's WebGL traces are used for long
series and all HTML output can be written fully offline.
"""

from dataclasses import asdict, dataclass, field, replace
from datetime import date, datetime
import html
import json
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import numpy as np


_DEFAULT_PALETTE = (
    "#2563eb",
    "#dc2626",
    "#059669",
    "#7c3aed",
    "#d97706",
    "#0891b2",
    "#be185d",
    "#4b5563",
)


@dataclass(frozen=True)
class ChartProfile:
    """Personal display preferences applied consistently across Omega charts."""

    name: str = "Omega default"
    template: str = "plotly_white"
    font_family: str = "Segoe UI, Arial, sans-serif"
    font_size: int = 13
    title_size: int = 20
    line_width: float = 2.5
    marker_size: float = 7.0
    show_grid: bool = True
    show_legend: bool = True
    range_slider: bool = True
    editable: bool = True
    scroll_zoom: bool = True
    show_spikes: bool = True
    hovermode: str = "x unified"
    legend_orientation: str = "h"
    background: str = "#ffffff"
    plot_background: str = "#ffffff"
    palette: tuple[str, ...] = field(default_factory=lambda: _DEFAULT_PALETTE)
    downsample_limit: int = 10_000
    default_width: int | None = None
    default_height: int = 720
    export_scale: int = 2

    def validated(self) -> "ChartProfile":
        palette = tuple(str(value) for value in self.palette if str(value).strip()) or _DEFAULT_PALETTE
        template = self.template if self.template in {
            "plotly_white", "plotly_dark", "simple_white", "ggplot2", "seaborn", "presentation", "none"
        } else "plotly_white"
        hovermode = self.hovermode if self.hovermode in {
            "x", "y", "closest", "x unified", "y unified", False
        } else "x unified"
        orientation = "v" if str(self.legend_orientation).lower().startswith("v") else "h"
        return replace(
            self,
            template=template,
            font_size=max(8, min(int(self.font_size), 32)),
            title_size=max(10, min(int(self.title_size), 48)),
            line_width=max(0.5, min(float(self.line_width), 12.0)),
            marker_size=max(1.0, min(float(self.marker_size), 30.0)),
            palette=palette,
            downsample_limit=max(200, int(self.downsample_limit)),
            default_height=max(320, int(self.default_height)),
            export_scale=max(1, min(int(self.export_scale), 8)),
            hovermode=hovermode,
            legend_orientation=orientation,
        )

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self.validated())
        payload["palette"] = list(payload["palette"])
        return payload

    @classmethod
    def from_dict(cls, payload: Mapping[str, Any]) -> "ChartProfile":
        known = {field.name for field in cls.__dataclass_fields__.values()}
        values = {key: value for key, value in dict(payload).items() if key in known}
        if "palette" in values:
            values["palette"] = tuple(values["palette"] or ())
        return cls(**values).validated()


class ChartProfileStore:
    """JSON profile store with named profiles and a selected default."""

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)

    def load_all(self) -> dict[str, ChartProfile]:
        if not self.path.exists():
            return {"Omega default": ChartProfile()}
        try:
            raw = json.loads(self.path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return {"Omega default": ChartProfile()}
        profiles = raw.get("profiles", raw) if isinstance(raw, dict) else {}
        result: dict[str, ChartProfile] = {}
        if isinstance(profiles, dict):
            for name, payload in profiles.items():
                if isinstance(payload, Mapping):
                    profile = ChartProfile.from_dict({**dict(payload), "name": str(name)})
                    result[profile.name] = profile
        return result or {"Omega default": ChartProfile()}

    def save(self, profile: ChartProfile) -> None:
        profiles = self.load_all()
        profile = profile.validated()
        profiles[profile.name] = profile
        self.path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "schema_version": 1,
            "profiles": {name: value.to_dict() for name, value in sorted(profiles.items())},
        }
        self.path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    def delete(self, name: str) -> bool:
        profiles = self.load_all()
        if name == "Omega default" or name not in profiles:
            return False
        del profiles[name]
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps({"schema_version": 1, "profiles": {k: v.to_dict() for k, v in profiles.items()}}, indent=2),
            encoding="utf-8",
        )
        return True


@dataclass(frozen=True)
class SeriesSpec:
    name: str
    x: Sequence[Any]
    y: Sequence[float]
    lower: Sequence[float] | None = None
    upper: Sequence[float] | None = None
    mode: str = "lines"
    yaxis: str = "y"
    visible: bool | str = True
    hover_template: str | None = None


def _plotly():
    try:
        import plotly.graph_objects as go
        from plotly.subplots import make_subplots
        import plotly.io as pio
    except ImportError as exc:  # pragma: no cover - depends on runtime packaging
        raise RuntimeError(
            "Interactive charts require Plotly. Run SETUP_OMEGA_FISH.bat or install plotly>=5.18."
        ) from exc
    return go, make_subplots, pio


def _numeric_x(values: Sequence[Any]) -> np.ndarray:
    if len(values) == 0:
        return np.asarray([], dtype=float)
    first = values[0]
    if isinstance(first, (datetime, date, np.datetime64)):
        return np.asarray([np.datetime64(value).astype("datetime64[ns]").astype(np.int64) for value in values], dtype=float)
    result = np.empty(len(values), dtype=float)
    for index, value in enumerate(values):
        try:
            result[index] = float(value)
        except (TypeError, ValueError):
            result[index] = float(index)
    return result


def lttb_downsample(
    x: Sequence[Any],
    y: Sequence[float],
    threshold: int,
) -> tuple[list[Any], list[float], list[int]]:
    """Largest-Triangle-Three-Buckets downsampling preserving peaks and endpoints.

    Returns sampled x, sampled y, and source indexes. Non-finite y observations are
    retained when the series is already below the threshold; for long series they
    are removed before the geometric sampling step.
    """

    if len(x) != len(y):
        raise ValueError("x and y must have equal length.")
    length = len(x)
    threshold = int(threshold)
    if threshold <= 0 or threshold >= length or length <= 2:
        return list(x), [float(v) for v in y], list(range(length))
    if threshold < 3:
        indexes = [0, length - 1][:threshold]
        return [x[i] for i in indexes], [float(y[i]) for i in indexes], indexes

    x_numeric = _numeric_x(x)
    y_numeric = np.asarray(y, dtype=float)
    finite = np.isfinite(x_numeric) & np.isfinite(y_numeric)
    finite_indexes = np.flatnonzero(finite)
    if len(finite_indexes) <= threshold:
        indexes = finite_indexes.tolist()
        return [x[i] for i in indexes], [float(y_numeric[i]) for i in indexes], indexes

    x_work = x_numeric[finite]
    y_work = y_numeric[finite]
    source = finite_indexes
    every = (len(x_work) - 2) / (threshold - 2)
    selected = [0]
    a = 0

    for bucket in range(threshold - 2):
        avg_start = int(np.floor((bucket + 1) * every)) + 1
        avg_end = int(np.floor((bucket + 2) * every)) + 1
        avg_end = min(avg_end, len(x_work))
        if avg_start >= avg_end:
            avg_x = x_work[min(avg_start, len(x_work) - 1)]
            avg_y = y_work[min(avg_start, len(y_work) - 1)]
        else:
            avg_x = float(np.mean(x_work[avg_start:avg_end]))
            avg_y = float(np.mean(y_work[avg_start:avg_end]))

        range_start = int(np.floor(bucket * every)) + 1
        range_end = int(np.floor((bucket + 1) * every)) + 1
        range_end = min(range_end, len(x_work) - 1)
        if range_end <= range_start:
            range_end = min(range_start + 1, len(x_work) - 1)

        point_ax = x_work[a]
        point_ay = y_work[a]
        segment_x = x_work[range_start:range_end]
        segment_y = y_work[range_start:range_end]
        areas = np.abs((point_ax - avg_x) * (segment_y - point_ay) - (point_ax - segment_x) * (avg_y - point_ay))
        offset = int(np.argmax(areas)) if len(areas) else 0
        a = min(range_start + offset, len(x_work) - 2)
        selected.append(a)

    selected.append(len(x_work) - 1)
    indexes = source[np.asarray(selected, dtype=int)].tolist()
    return [x[i] for i in indexes], [float(y_numeric[i]) for i in indexes], indexes


def _finite_range(values: Iterable[float]) -> tuple[float, float] | None:
    array = np.asarray(list(values), dtype=float)
    array = array[np.isfinite(array)]
    if not len(array):
        return None
    return float(np.min(array)), float(np.max(array))


class InteractiveChartFactory:
    """Build consistent Plotly figures for all expert-workflow diagnostics."""

    def __init__(self, profile: ChartProfile | None = None) -> None:
        self.profile = (profile or ChartProfile()).validated()

    @property
    def config(self) -> dict[str, Any]:
        return {
            "responsive": True,
            "scrollZoom": self.profile.scroll_zoom,
            "editable": self.profile.editable,
            "displaylogo": False,
            "toImageButtonOptions": {
                "format": "png",
                "filename": "omega_fish_chart",
                "height": self.profile.default_height,
                "width": self.profile.default_width or 1400,
                "scale": self.profile.export_scale,
            },
            "modeBarButtonsToAdd": [
                "drawline",
                "drawopenpath",
                "drawrect",
                "drawcircle",
                "eraseshape",
                "toggleSpikelines",
            ],
        }

    def _base_layout(self, title: str, x_title: str = "", y_title: str = "") -> dict[str, Any]:
        profile = self.profile
        legend = {
            "orientation": profile.legend_orientation,
            "yanchor": "bottom" if profile.legend_orientation == "h" else "top",
            "y": 1.02 if profile.legend_orientation == "h" else 1.0,
            "xanchor": "right" if profile.legend_orientation == "h" else "left",
            "x": 1.0 if profile.legend_orientation == "h" else 1.02,
        }
        axis_common = {
            "showgrid": profile.show_grid,
            "showspikes": profile.show_spikes,
            "spikemode": "across",
            "spikesnap": "cursor",
            "showline": True,
            "mirror": True,
            "zeroline": False,
        }
        return {
            "title": {"text": title, "font": {"size": profile.title_size}, "x": 0.01, "xanchor": "left"},
            "template": profile.template,
            "font": {"family": profile.font_family, "size": profile.font_size},
            "paper_bgcolor": profile.background,
            "plot_bgcolor": profile.plot_background,
            "hovermode": profile.hovermode,
            "showlegend": profile.show_legend,
            "legend": legend,
            "height": profile.default_height,
            "width": profile.default_width,
            "margin": {"l": 75, "r": 55, "t": 90, "b": 70},
            "xaxis": {**axis_common, "title": x_title, "rangeslider": {"visible": profile.range_slider}},
            "yaxis": {**axis_common, "title": y_title},
            "dragmode": "zoom",
            "newshape": {"line": {"width": 2}},
        }

    def time_series(
        self,
        series: Sequence[SeriesSpec],
        *,
        title: str = "Time series",
        x_title: str = "Year",
        y_title: str = "Value",
        normalize: bool = False,
        log_y: bool = False,
        reference_lines: Mapping[str, float] | None = None,
    ):
        go, _make_subplots, _pio = _plotly()
        figure = go.Figure()
        buttons_visibility: list[list[bool]] = []
        trace_count = 0
        for index, spec in enumerate(series):
            x_values, y_values, indexes = lttb_downsample(spec.x, spec.y, self.profile.downsample_limit)
            y_array = np.asarray(y_values, dtype=float)
            if normalize:
                finite = y_array[np.isfinite(y_array)]
                scale = float(finite[0]) if len(finite) and abs(float(finite[0])) > 1e-12 else float(np.nanmean(finite)) if len(finite) else 1.0
                y_array = y_array / max(abs(scale), 1e-12)
            color = self.profile.palette[index % len(self.profile.palette)]

            if spec.lower is not None and spec.upper is not None:
                lower = np.asarray(spec.lower, dtype=float)[indexes]
                upper = np.asarray(spec.upper, dtype=float)[indexes]
                if normalize:
                    lower = lower / max(abs(scale), 1e-12)
                    upper = upper / max(abs(scale), 1e-12)
                figure.add_trace(
                    go.Scattergl(
                        x=x_values,
                        y=upper,
                        mode="lines",
                        line={"width": 0},
                        hoverinfo="skip",
                        showlegend=False,
                        name=f"{spec.name} upper",
                        visible=spec.visible,
                    )
                )
                figure.add_trace(
                    go.Scattergl(
                        x=x_values,
                        y=lower,
                        mode="lines",
                        line={"width": 0},
                        fill="tonexty",
                        fillcolor=_rgba(color, 0.16),
                        hoverinfo="skip",
                        showlegend=False,
                        name=f"{spec.name} uncertainty",
                        visible=spec.visible,
                    )
                )
                trace_count += 2

            figure.add_trace(
                go.Scattergl(
                    x=x_values,
                    y=y_array,
                    mode=spec.mode,
                    name=spec.name,
                    line={"width": self.profile.line_width, "color": color},
                    marker={"size": self.profile.marker_size, "color": color},
                    yaxis=spec.yaxis,
                    visible=spec.visible,
                    hovertemplate=spec.hover_template or "%{x}<br>%{y:.5g}<extra>%{fullData.name}</extra>",
                )
            )
            trace_count += 1

        layout = self._base_layout(title, x_title, "Relative to first value" if normalize else y_title)
        layout["yaxis"]["type"] = "log" if log_y else "linear"
        if any(spec.yaxis == "y2" for spec in series):
            layout["yaxis2"] = {
                "title": "Secondary axis",
                "overlaying": "y",
                "side": "right",
                "showgrid": False,
                "showline": True,
                "mirror": True,
                "zeroline": False,
                "showspikes": self.profile.show_spikes,
                "spikemode": "across",
                "spikesnap": "cursor",
            }
            layout["margin"]["r"] = 90
        if reference_lines:
            shapes = []
            annotations = []
            for label, value in reference_lines.items():
                shapes.append({
                    "type": "line", "xref": "paper", "x0": 0, "x1": 1,
                    "yref": "y", "y0": float(value), "y1": float(value),
                    "line": {"dash": "dash", "width": 1.5},
                })
                annotations.append({
                    "xref": "paper", "x": 1, "yref": "y", "y": float(value),
                    "text": str(label), "showarrow": False, "xanchor": "left",
                })
            layout["shapes"] = shapes
            layout["annotations"] = annotations

        # User-facing transform buttons remain available even when the figure is generated from a fixed source.
        layout["updatemenus"] = [
            {
                "type": "buttons",
                "direction": "right",
                "x": 0,
                "y": 1.15,
                "buttons": [
                    {"label": "Linear Y", "method": "relayout", "args": [{"yaxis.type": "linear"}]},
                    {"label": "Log Y", "method": "relayout", "args": [{"yaxis.type": "log"}]},
                    {"label": "Show slider", "method": "relayout", "args": [{"xaxis.rangeslider.visible": True}]},
                    {"label": "Hide slider", "method": "relayout", "args": [{"xaxis.rangeslider.visible": False}]},
                ],
            }
        ]
        figure.update_layout(**layout)
        return figure

    def residual_heatmap(
        self,
        matrix: Sequence[Sequence[float]],
        *,
        x_labels: Sequence[Any] | None = None,
        y_labels: Sequence[Any] | None = None,
        title: str = "Residual heatmap",
        z_title: str = "Standardised residual",
    ):
        go, _make_subplots, _pio = _plotly()
        z = np.asarray(matrix, dtype=float)
        if z.ndim != 2:
            raise ValueError("Residual heatmap requires a two-dimensional matrix.")
        finite = z[np.isfinite(z)]
        limit = max(float(np.nanpercentile(np.abs(finite), 95)) if len(finite) else 1.0, 1e-6)
        figure = go.Figure(
            data=go.Heatmap(
                z=z,
                x=list(x_labels) if x_labels is not None else list(range(z.shape[1])),
                y=list(y_labels) if y_labels is not None else list(range(z.shape[0])),
                zmid=0,
                zmin=-limit,
                zmax=limit,
                colorscale="RdBu",
                reversescale=True,
                colorbar={"title": z_title},
                hovertemplate="X=%{x}<br>Y=%{y}<br>Residual=%{z:.3f}<extra></extra>",
            )
        )
        layout = self._base_layout(title, "Observation / year", "Fleet / age / source")
        layout["xaxis"]["rangeslider"] = {"visible": False}
        figure.update_layout(**layout)
        return figure

    def optimization_surface(
        self,
        rows: Sequence[Mapping[str, Any]],
        *,
        x_key: str,
        y_key: str,
        value_key: str,
        maximize: bool = False,
        title: str = "Parameter optimization surface",
    ):
        """MetaTrader-style parameter grid with an explicit best combination."""

        go, _make_subplots, _pio = _plotly()
        valid: list[tuple[float, float, float]] = []
        for row in rows:
            x_value = _as_float(row.get(x_key))
            y_value = _as_float(row.get(y_key))
            score = _as_float(row.get(value_key))
            if x_value is not None and y_value is not None and score is not None:
                valid.append((x_value, y_value, score))
        if not valid:
            raise ValueError("The optimization grid needs numeric X parameter, Y parameter and objective/fitness values.")
        x_values = sorted({row[0] for row in valid})
        y_values = sorted({row[1] for row in valid})
        x_lookup = {value: index for index, value in enumerate(x_values)}
        y_lookup = {value: index for index, value in enumerate(y_values)}
        cells: dict[tuple[int, int], list[float]] = {}
        for x_value, y_value, score in valid:
            cells.setdefault((y_lookup[y_value], x_lookup[x_value]), []).append(score)
        matrix = np.full((len(y_values), len(x_values)), np.nan, dtype=float)
        for (row_index, column_index), values in cells.items():
            matrix[row_index, column_index] = float(np.mean(values))
        best = max(valid, key=lambda row: row[2]) if maximize else min(valid, key=lambda row: row[2])
        figure = go.Figure()
        figure.add_trace(
            go.Heatmap(
                x=x_values,
                y=y_values,
                z=matrix,
                colorscale="Viridis" if maximize else "Viridis_r",
                colorbar={"title": value_key.replace("_", " ").title()},
                hovertemplate=(
                    f"{x_key}=%{{x:.6g}}<br>{y_key}=%{{y:.6g}}<br>"
                    f"{value_key}=%{{z:.6g}}<extra></extra>"
                ),
            )
        )
        figure.add_trace(
            go.Scatter(
                x=[best[0]],
                y=[best[1]],
                mode="markers+text",
                text=[f"Best: {best[2]:.6g}"],
                textposition="top center",
                name="Best parameter set",
                marker={"symbol": "star", "size": 18, "color": self.profile.palette[1], "line": {"width": 2, "color": self.profile.palette[-1]}},
                hovertemplate=f"Best<br>{x_key}=%{{x:.6g}}<br>{y_key}=%{{y:.6g}}<br>{value_key}={best[2]:.6g}<extra></extra>",
            )
        )
        layout = self._base_layout(title, x_key.replace("_", " ").title(), y_key.replace("_", " ").title())
        layout["xaxis"]["rangeslider"] = {"visible": False}
        layout["annotations"] = [
            {
                "xref": "paper",
                "yref": "paper",
                "x": 0,
                "y": 1.08,
                "showarrow": False,
                "xanchor": "left",
                "text": f"Goal: {'maximize' if maximize else 'minimize'} {value_key.replace('_', ' ')}",
            }
        ]
        figure.update_layout(**layout)
        return figure

    def jitter_distribution(
        self,
        runs: Sequence[Mapping[str, Any]],
        *,
        value_key: str = "objective",
        group_key: str = "optimizer",
        title: str = "Jitter and multi-start distribution",
    ):
        go, _make_subplots, _pio = _plotly()
        groups: dict[str, list[float]] = {}
        for row in runs:
            value = _as_float(row.get(value_key))
            if value is None:
                continue
            groups.setdefault(str(row.get(group_key, "All runs")), []).append(value)
        figure = go.Figure()
        for index, (name, values) in enumerate(sorted(groups.items())):
            color = self.profile.palette[index % len(self.profile.palette)]
            figure.add_trace(
                go.Violin(
                    y=values,
                    name=name,
                    box_visible=True,
                    meanline_visible=True,
                    points="all" if len(values) <= 250 else "outliers",
                    jitter=0.3,
                    marker={"size": max(3.0, self.profile.marker_size - 2), "color": color},
                    line={"color": color, "width": self.profile.line_width},
                )
            )
        layout = self._base_layout(title, "Optimizer / configuration", value_key.replace("_", " ").title())
        layout["xaxis"]["rangeslider"] = {"visible": False}
        figure.update_layout(**layout)
        return figure

    def optimizer_agreement(
        self,
        rows: Sequence[Mapping[str, Any]],
        *,
        x_key: str = "objective",
        y_key: str = "terminal_depletion",
        label_key: str = "optimizer",
        size_key: str | None = None,
        title: str = "Multi-optimizer agreement",
    ):
        go, _make_subplots, _pio = _plotly()
        groups: dict[str, list[Mapping[str, Any]]] = {}
        for row in rows:
            groups.setdefault(str(row.get(label_key, "run")), []).append(row)
        figure = go.Figure()
        for index, (name, group) in enumerate(sorted(groups.items())):
            x = [_as_float(row.get(x_key)) for row in group]
            y = [_as_float(row.get(y_key)) for row in group]
            valid = [(a, b, row) for a, b, row in zip(x, y, group) if a is not None and b is not None]
            if not valid:
                continue
            color = self.profile.palette[index % len(self.profile.palette)]
            sizes = []
            for _a, _b, row in valid:
                raw = _as_float(row.get(size_key)) if size_key else None
                sizes.append(max(self.profile.marker_size, min(30.0, raw or self.profile.marker_size)))
            figure.add_trace(
                go.Scattergl(
                    x=[value[0] for value in valid],
                    y=[value[1] for value in valid],
                    mode="markers+text" if len(valid) <= 12 else "markers",
                    text=[str(value[2].get("run", "")) for value in valid],
                    textposition="top center",
                    name=name,
                    marker={"size": sizes, "color": color, "opacity": 0.78, "line": {"width": 1}},
                    customdata=[json.dumps(value[2], default=str) for value in valid],
                    hovertemplate=f"{x_key}=%{{x:.6g}}<br>{y_key}=%{{y:.6g}}<extra>{html.escape(name)}</extra>",
                )
            )
        layout = self._base_layout(title, x_key.replace("_", " ").title(), y_key.replace("_", " ").title())
        layout["xaxis"]["rangeslider"] = {"visible": False}
        figure.update_layout(**layout)
        return figure

    def likelihood_conflict(
        self,
        components: Sequence[Mapping[str, Any]],
        *,
        component_key: str = "component",
        value_key: str = "delta_nll",
        preferred_key: str | None = "preferred_value",
        title: str = "Likelihood-component conflict",
    ):
        go, _make_subplots, _pio = _plotly()
        labels = [str(row.get(component_key, f"component {i + 1}")) for i, row in enumerate(components)]
        values = [float(row.get(value_key, 0.0) or 0.0) for row in components]
        text = []
        for row, value in zip(components, values):
            preferred = row.get(preferred_key) if preferred_key else None
            suffix = f"<br>Preferred: {preferred}" if preferred is not None else ""
            text.append(f"ΔNLL: {value:.5g}{suffix}")
        figure = go.Figure(
            go.Bar(
                x=values,
                y=labels,
                orientation="h",
                text=text,
                hovertemplate="%{y}<br>%{text}<extra></extra>",
                marker={"color": values, "colorscale": "Viridis", "showscale": True, "colorbar": {"title": "ΔNLL"}},
            )
        )
        layout = self._base_layout(title, "Objective change / conflict strength", "Likelihood component")
        layout["xaxis"]["rangeslider"] = {"visible": False}
        layout["yaxis"]["categoryorder"] = "total ascending"
        figure.update_layout(**layout)
        return figure

    def likelihood_profile(
        self,
        points: Sequence[Mapping[str, Any]],
        *,
        parameter_key: str = "value",
        objective_key: str = "objective",
        component_keys: Sequence[str] | None = None,
        title: str = "Likelihood profile",
        parameter_label: str = "Parameter value",
    ):
        go, _make_subplots, _pio = _plotly()
        x = np.asarray([float(row[parameter_key]) for row in points], dtype=float)
        y = np.asarray([float(row[objective_key]) for row in points], dtype=float)
        order = np.argsort(x)
        x = x[order]
        y = y[order]
        delta = y - np.nanmin(y)
        figure = go.Figure()
        figure.add_trace(
            go.Scatter(
                x=x,
                y=delta,
                mode="lines+markers",
                name="Total objective",
                line={"width": self.profile.line_width, "color": self.profile.palette[0]},
                marker={"size": self.profile.marker_size},
                hovertemplate=f"{parameter_label}=%{{x:.6g}}<br>Δ objective=%{{y:.5g}}<extra></extra>",
            )
        )
        for index, key in enumerate(component_keys or (), 1):
            values = np.asarray([float(points[i].get(key, np.nan)) for i in order], dtype=float)
            if np.isfinite(values).any():
                values = values - np.nanmin(values)
                figure.add_trace(
                    go.Scatter(
                        x=x,
                        y=values,
                        mode="lines",
                        name=key.replace("_", " ").title(),
                        line={"width": max(1.0, self.profile.line_width - 0.5), "color": self.profile.palette[index % len(self.profile.palette)]},
                    )
                )
        for threshold, label in ((1.92, "Approx. 95% one-parameter"), (0.5, "Approx. 68% one-parameter")):
            figure.add_hline(y=threshold, line_dash="dash", annotation_text=label, annotation_position="top right")
        layout = self._base_layout(title, parameter_label, "Δ objective")
        layout["xaxis"]["rangeslider"] = {"visible": False}
        figure.update_layout(**layout)
        return figure

    def retrospective(
        self,
        full: Mapping[Any, float],
        peels: Sequence[Mapping[Any, float]],
        *,
        title: str = "Retrospective analysis",
        y_title: str = "Estimated quantity",
        mohn_rho: float | None = None,
    ):
        series = [SeriesSpec("Full model", list(full), list(full.values()), mode="lines+markers")]
        for index, peel in enumerate(peels, 1):
            series.append(SeriesSpec(f"Peel {index}", list(peel), list(peel.values()), mode="lines"))
        suffix = f" — Mohn's ρ={mohn_rho:.3f}" if mohn_rho is not None and np.isfinite(mohn_rho) else ""
        figure = self.time_series(series, title=title + suffix, y_title=y_title)
        figure.update_layout(
            updatemenus=[
                {
                    "type": "dropdown",
                    "x": 0,
                    "y": 1.15,
                    "buttons": [
                        {"label": "All peels", "method": "update", "args": [{"visible": [True] * len(series)}]},
                        {"label": "Full only", "method": "update", "args": [{"visible": [True] + [False] * (len(series) - 1)}]},
                    ],
                }
            ]
        )
        return figure

    def hindcast(
        self,
        rows: Sequence[Mapping[str, Any]],
        *,
        x_key: str = "year",
        observed_key: str = "observed",
        predicted_key: str = "predicted",
        lower_key: str | None = "lower",
        upper_key: str | None = "upper",
        title: str = "Hindcast prediction",
        mase: float | None = None,
    ):
        x = [row.get(x_key) for row in rows]
        observed = [float(row.get(observed_key, np.nan)) for row in rows]
        predicted = [float(row.get(predicted_key, np.nan)) for row in rows]
        lower = [float(row.get(lower_key, np.nan)) for row in rows] if lower_key else None
        upper = [float(row.get(upper_key, np.nan)) for row in rows] if upper_key else None
        suffix = f" — MASE={mase:.3f}" if mase is not None and np.isfinite(mase) else ""
        return self.time_series(
            [
                SeriesSpec("Observed", x, observed, mode="markers"),
                SeriesSpec("Predicted", x, predicted, lower=lower, upper=upper, mode="lines+markers"),
            ],
            title=title + suffix,
            y_title="Observation / prediction",
        )

    def ensemble_fan(
        self,
        years: Sequence[Any],
        median: Sequence[float],
        lower: Sequence[float],
        upper: Sequence[float],
        members: Mapping[str, Sequence[float]] | None = None,
        *,
        title: str = "Structural model ensemble",
        y_title: str = "Biomass / depletion",
    ):
        series: list[SeriesSpec] = []
        for name, values in (members or {}).items():
            series.append(SeriesSpec(name, years, values, mode="lines", visible="legendonly"))
        series.append(SeriesSpec("Ensemble median", years, median, lower=lower, upper=upper, mode="lines+markers"))
        return self.time_series(series, title=title, y_title=y_title)

    def mse_tradeoff(
        self,
        rows: Sequence[Mapping[str, Any]],
        *,
        x_key: str = "average_catch",
        y_key: str = "probability_above_limit",
        color_key: str = "catch_cv",
        size_key: str = "closure_probability",
        label_key: str = "procedure",
        title: str = "Closed-loop MSE trade-off frontier",
    ):
        go, _make_subplots, _pio = _plotly()
        valid = []
        for row in rows:
            x = _as_float(row.get(x_key)); y = _as_float(row.get(y_key))
            if x is None or y is None:
                continue
            color = _as_float(row.get(color_key)) or 0.0
            size = _as_float(row.get(size_key)) or 0.0
            valid.append((x, y, color, size, row))
        sizes = [10 + 35 * max(0.0, min(1.0, item[3])) for item in valid]
        figure = go.Figure(
            go.Scattergl(
                x=[item[0] for item in valid],
                y=[item[1] for item in valid],
                mode="markers+text" if len(valid) <= 18 else "markers",
                text=[str(item[4].get(label_key, "")) for item in valid],
                textposition="top center",
                marker={
                    "size": sizes,
                    "color": [item[2] for item in valid],
                    "colorscale": "Viridis",
                    "showscale": True,
                    "colorbar": {"title": color_key.replace("_", " ")},
                    "opacity": 0.8,
                    "line": {"width": 1},
                },
                customdata=[item[3] for item in valid],
                hovertemplate=(
                    f"{x_key}=%{{x:.5g}}<br>{y_key}=%{{y:.3f}}<br>"
                    f"{color_key}=%{{marker.color:.4g}}<br>{size_key}=%{{customdata:.3f}}<extra>%{{text}}</extra>"
                ),
            )
        )
        layout = self._base_layout(title, x_key.replace("_", " ").title(), y_key.replace("_", " ").title())
        layout["xaxis"]["rangeslider"] = {"visible": False}
        figure.update_layout(**layout)
        return figure

    def interval_coverage(
        self,
        rows: Sequence[Mapping[str, Any]],
        *,
        nominal_key: str = "nominal",
        empirical_key: str = "empirical",
        parameter_key: str = "parameter",
        title: str = "Interval-coverage testing",
    ):
        go, _make_subplots, _pio = _plotly()
        groups: dict[str, list[tuple[float, float]]] = {}
        for row in rows:
            nominal = _as_float(row.get(nominal_key)); empirical = _as_float(row.get(empirical_key))
            if nominal is None or empirical is None:
                continue
            groups.setdefault(str(row.get(parameter_key, "Overall")), []).append((nominal, empirical))
        figure = go.Figure()
        for index, (name, values) in enumerate(sorted(groups.items())):
            values.sort()
            figure.add_trace(
                go.Scatter(
                    x=[value[0] for value in values],
                    y=[value[1] for value in values],
                    mode="lines+markers",
                    name=name,
                    line={"width": self.profile.line_width, "color": self.profile.palette[index % len(self.profile.palette)]},
                    marker={"size": self.profile.marker_size},
                )
            )
        figure.add_trace(
            go.Scatter(x=[0, 1], y=[0, 1], mode="lines", name="Ideal coverage", line={"dash": "dash", "width": 2})
        )
        layout = self._base_layout(title, "Nominal interval coverage", "Empirical coverage")
        layout["xaxis"].update({"rangeslider": {"visible": False}, "range": [0, 1]})
        layout["yaxis"].update({"range": [0, 1]})
        figure.update_layout(**layout)
        return figure

    def write_html(
        self,
        figure,
        output: str | Path,
        *,
        title: str | None = None,
        include_plotlyjs: bool | str = "directory",
        auto_open: bool = False,
    ) -> Path:
        _go, _make_subplots, pio = _plotly()
        output_path = Path(output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        pio.write_html(
            figure,
            file=str(output_path),
            config=self.config,
            include_plotlyjs=include_plotlyjs,
            full_html=True,
            auto_open=auto_open,
            default_width="100%",
            default_height="100%",
            validate=True,
        )
        return output_path

    def write_dashboard(
        self,
        figures: Mapping[str, Any],
        output: str | Path,
        *,
        title: str = "Omega FISH interactive diagnostics",
        metadata: Mapping[str, Any] | None = None,
        include_plotlyjs: bool | str = "directory",
    ) -> Path:
        """Write a tabbed, responsive dashboard with a single Plotly bundle."""

        _go, _make_subplots, pio = _plotly()
        output_path = Path(output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        if not figures:
            raise ValueError("At least one figure is required for a dashboard.")

        plot_divs: list[str] = []
        tabs: list[str] = []
        first = True
        external_plotly_script = ""
        fragment_plotly_setting: bool | str = include_plotlyjs
        if include_plotlyjs == "directory":
            from plotly.offline import get_plotlyjs

            js_path = output_path.parent / "plotly.min.js"
            if not js_path.exists():
                js_path.write_text(get_plotlyjs(), encoding="utf-8")
            external_plotly_script = '<script src="plotly.min.js"></script>'
            fragment_plotly_setting = False
        for index, (label, figure) in enumerate(figures.items()):
            div_id = f"omega-chart-{index}"
            fragment = pio.to_html(
                figure,
                include_plotlyjs=fragment_plotly_setting if first else False,
                full_html=False,
                config=self.config,
                div_id=div_id,
                default_width="100%",
                default_height=f"{self.profile.default_height}px",
            )
            active = " active" if first else ""
            tabs.append(f'<button class="tab-button{active}" data-target="panel-{index}">{html.escape(label)}</button>')
            plot_divs.append(f'<section id="panel-{index}" class="chart-panel{active}">{fragment}</section>')
            first = False

        meta_html = ""
        if metadata:
            rows = "".join(
                f"<tr><th>{html.escape(str(key))}</th><td>{html.escape(str(value))}</td></tr>"
                for key, value in metadata.items()
            )
            meta_html = f'<details><summary>Run metadata and provenance</summary><table>{rows}</table></details>'

        document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
{external_plotly_script}
<style>
:root {{ color-scheme: light dark; --header:#0b1f33; --accent:#2563eb; --panel:#ffffff; --page:#eef3f8; --text:#172033; }}
* {{ box-sizing:border-box; }}
body {{ margin:0; background:var(--page); color:var(--text); font-family:{html.escape(self.profile.font_family)}; }}
header {{ background:var(--header); color:white; padding:18px 24px; position:sticky; top:0; z-index:20; box-shadow:0 2px 12px rgba(0,0,0,.18); }}
header h1 {{ margin:0; font-size:24px; }}
header p {{ margin:5px 0 0; color:#c7d5e3; }}
.toolbar {{ display:flex; flex-wrap:wrap; gap:8px; padding:12px 18px; background:#dce6f0; position:sticky; top:76px; z-index:19; }}
.tab-button {{ border:1px solid #9fb3c8; background:#fff; color:#243b53; border-radius:8px; padding:9px 13px; cursor:pointer; font-weight:600; }}
.tab-button.active {{ background:var(--accent); color:#fff; border-color:var(--accent); }}
main {{ padding:16px; }}
.chart-panel {{ display:none; background:var(--panel); border-radius:12px; box-shadow:0 2px 14px rgba(36,59,83,.12); overflow:hidden; }}
.chart-panel.active {{ display:block; }}
details {{ margin:16px; padding:12px; background:white; border-radius:10px; }}
table {{ border-collapse:collapse; width:100%; margin-top:10px; }} th,td {{ text-align:left; padding:7px; border-bottom:1px solid #d9e2ec; }}
@media (prefers-color-scheme: dark) {{ :root {{ --panel:#162536; --page:#0f1720; --text:#e5edf5; }} .toolbar{{background:#1c3044}} .tab-button{{background:#162536;color:#e5edf5}} details{{background:#162536}} }}
</style>
</head>
<body>
<header><h1>{html.escape(title)}</h1><p>Scroll to zoom, drag to select, double-click to reset, use the modebar to annotate or export, and edit titles when enabled.</p></header>
<nav class="toolbar">{''.join(tabs)}</nav>
<main>{''.join(plot_divs)}{meta_html}</main>
<script>
document.querySelectorAll('.tab-button').forEach(button => button.addEventListener('click', () => {{
  document.querySelectorAll('.tab-button,.chart-panel').forEach(node => node.classList.remove('active'));
  button.classList.add('active');
  const panel = document.getElementById(button.dataset.target);
  panel.classList.add('active');
  panel.querySelectorAll('.plotly-graph-div').forEach(div => Plotly.Plots.resize(div));
}}));
window.addEventListener('resize', () => document.querySelectorAll('.plotly-graph-div').forEach(div => Plotly.Plots.resize(div)));
</script>
</body>
</html>"""
        output_path.write_text(document, encoding="utf-8")
        return output_path


def _rgba(hex_color: str, alpha: float) -> str:
    value = str(hex_color).strip().lstrip("#")
    if len(value) == 3:
        value = "".join(character * 2 for character in value)
    if len(value) != 6:
        return f"rgba(37,99,235,{alpha:.3f})"
    try:
        red, green, blue = (int(value[index:index + 2], 16) for index in (0, 2, 4))
    except ValueError:
        return f"rgba(37,99,235,{alpha:.3f})"
    return f"rgba({red},{green},{blue},{max(0.0, min(1.0, alpha)):.3f})"


def _as_float(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if np.isfinite(number) else None


def chart_profile_schema() -> dict[str, Any]:
    """Machine-readable settings schema for desktop and future web clients."""

    return {
        "schema_version": 1,
        "themes": ["plotly_white", "plotly_dark", "simple_white", "ggplot2", "seaborn", "presentation", "none"],
        "hover_modes": ["x unified", "y unified", "closest", "x", "y"],
        "editable_fields": [
            "name", "template", "font_family", "font_size", "title_size", "line_width", "marker_size",
            "show_grid", "show_legend", "range_slider", "editable", "scroll_zoom", "show_spikes",
            "hovermode", "legend_orientation", "background", "plot_background", "palette", "downsample_limit",
            "default_width", "default_height", "export_scale",
        ],
    }
