from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DATASET = ROOT / "Data_Sets" / "DPIRD" / "West_Australian_Dhufish"
READY = DATASET / "Omega_Ready"
RESULTS = DATASET / "Results"
REPORT = RESULTS / "Report"


def records(frame: pd.DataFrame) -> list[dict[str, object]]:
    return json.loads(frame.where(pd.notna(frame), None).to_json(orient="records"))


def build() -> Path:
    REPORT.mkdir(parents=True, exist_ok=True)
    summary = pd.read_csv(RESULTS / "stress_test_summary.csv")
    trajectories = pd.read_csv(RESULTS / "stress_test_trajectories.csv")
    published = pd.read_csv(READY / "published_assessment_outputs_digitised.csv")
    sources_manifest = json.loads((READY / "source_manifest.json").read_text(encoding="utf-8"))

    published_series = published[["year", "published_wcb_relative_female_spawning_biomass"]].rename(
        columns={"published_wcb_relative_female_spawning_biomass": "published_dpird"}
    )
    selected = {
        "base_public_working": "omega_base",
        "natural_mortality_0.09": "omega_M_0_09",
        "natural_mortality_0.13": "omega_M_0_13",
        "post_2023_retention_L50_300": "omega_post_2023_retention_300",
    }
    comparison = published_series.copy()
    for run, field in selected.items():
        values = trajectories.loc[trajectories["run"] == run, ["year", "depletion"]].rename(columns={"depletion": field})
        comparison = comparison.merge(values, on="year", how="left")

    rmse_rows = []
    for run, group in trajectories.groupby("run"):
        joined = group[["year", "depletion"]].merge(published_series, on="year", how="inner").dropna()
        rmse = float(np.sqrt(np.mean((joined["depletion"] - joined["published_dpird"]) ** 2)))
        rmse_rows.append({"run": run, "trajectory_rmse_vs_digitised_dpird": rmse})
    rmse = pd.DataFrame(rmse_rows)
    summary = summary.merge(rmse, on="run", how="left")
    summary["absolute_terminal_difference"] = summary["difference_from_published"].abs()

    base = summary.set_index("run").loc["base_public_working"]
    seed = summary.set_index("run").loc["optimizer_seed_8302"]
    no_age = summary.set_index("run").loc["no_age_compositions"]
    low_m = summary.set_index("run").loc["natural_mortality_0.09"]
    post_retention = summary.set_index("run").loc["post_2023_retention_L50_300"]
    closest = summary.sort_values("absolute_terminal_difference").iloc[0]

    metric_rows = pd.DataFrame(
        [
            {
                "omega_baseline": float(base["terminal_depletion"]),
                "dpird_published": 0.15,
                "closest_public_stress_test": float(closest["terminal_depletion"]),
                "stress_test_count": int(len(summary)),
                "optimizer_seed_spread": abs(float(base["terminal_depletion"]) - float(seed["terminal_depletion"])),
            }
        ]
    )

    source_publication = {
        "id": "dpird-publications",
        "label": "Official DPIRD public assessment material",
        "href": "https://library.dpird.wa.gov.au/fish_rar/2/",
        "query": {
            "sql": "SELECT year, published_wcb_relative_female_spawning_biomass FROM read_csv_auto('Data_Sets/DPIRD/West_Australian_Dhufish/Omega_Ready/published_assessment_outputs_digitised.csv') WHERE year = 2024;",
            "description": "Four official DPIRD publications preserved with SHA-256 hashes in the dataset source manifest.",
            "engine": "DuckDB over a reproducible digitisation of official PDF publications",
            "language": "SQL",
            "executed_at": sources_manifest["generated_utc"],
            "tables_used": [source["file"] for source in sources_manifest["sources"]],
            "filters": ["WA Dhufish", "West Coast Bioregion", "official DPIRD sources only"],
            "metric_definitions": ["Brel = female spawning biomass divided by estimated unfished female spawning biomass"],
        },
    }
    source_analysis = {
        "id": "omega-stress-tests",
        "label": "Omega public reconstruction stress tests",
        "path": "Data_Sets/DPIRD/West_Australian_Dhufish/Results/stress_test_summary.csv",
        "query": {
            "sql": "SELECT * FROM read_csv_auto('Data_Sets/DPIRD/West_Australian_Dhufish/Results/stress_test_summary.csv');",
            "description": "Reproducible 15-run stress test generated by tools/run_dpird_dhufish_public_stress_test.py.",
            "engine": "DuckDB over Omega Python age-structured engine output",
            "language": "SQL",
            "executed_at": datetime.now(timezone.utc).isoformat(),
            "tables_used": [
                "Omega_Ready/dpird_wa_dhufish_public_reconstruction.csv",
                "Omega_Ready/age_composition.csv",
                "Omega_Ready/parameter_register.csv",
            ],
            "filters": ["years 1975-2024", "public evidence only", "no confidential or unreleased DPIRD inputs"],
            "metric_definitions": [
                "Terminal depletion = Omega terminal female spawning biomass / Omega unfished female spawning biomass",
                "Trajectory RMSE = root mean squared annual difference from digitised DPIRD Figure 3.21 WCB Brel",
            ],
        },
    }
    source_dataset = {
        "id": "public-dataset",
        "label": "WA Dhufish public-evidence dataset",
        "path": "Data_Sets/DPIRD/West_Australian_Dhufish/Omega_Ready/dpird_wa_dhufish_public_reconstruction.csv",
        "query": {
            "sql": "SELECT * FROM read_csv_auto('Data_Sets/DPIRD/West_Australian_Dhufish/Omega_Ready/dpird_wa_dhufish_public_reconstruction.csv');",
            "description": "Catch, CPUE and age-composition values digitised from official figures with exact published parameters stored separately.",
            "engine": "DuckDB over reproducible image-digitisation output",
            "language": "SQL",
            "tables_used": [
                "RAR2 Figure 3.15 retained catch",
                "RAR2 Figure 3.17 commercial CPUE",
                "RAR2 Figure 3.19 age compositions",
                "RAR2 Figure 3.21 assessment outputs",
            ],
            "filters": ["public figures only", "chart-derived values explicitly labelled approximate"],
        },
    }
    source_list = [source_publication, source_dataset, source_analysis]

    cards = [
        {
            "id": "card-omega",
            "dataset": "headline",
            "sourceId": "omega-stress-tests",
            "description": "Working public-evidence reconstruction; not the accepted DPIRD model.",
            "metrics": [{"label": "Omega baseline terminal B/B0", "field": "omega_baseline", "format": "number"}],
        },
        {
            "id": "card-dpird",
            "dataset": "headline",
            "sourceId": "dpird-publications",
            "description": "DPIRD 2025 WCB central estimate.",
            "metrics": [{"label": "DPIRD published terminal B/B0", "field": "dpird_published", "format": "number"}],
        },
        {
            "id": "card-closest",
            "dataset": "headline",
            "sourceId": "omega-stress-tests",
            "description": f"Closest of 15 tested variants: {closest['run']}; closeness is not validation.",
            "metrics": [{"label": "Closest tested terminal B/B0", "field": "closest_public_stress_test", "format": "number"}],
        },
        {
            "id": "card-instability",
            "dataset": "headline",
            "sourceId": "omega-stress-tests",
            "description": "Difference between two optimizer seeds under the same public configuration.",
            "metrics": [{"label": "Optimizer-seed terminal spread", "field": "optimizer_seed_spread", "format": "number"}],
        },
    ]

    chart = {
        "id": "trajectory-comparison",
        "title": "Relative female spawning biomass trajectories",
        "subtitle": "Omega public reconstruction remains above the digitised DPIRD trajectory; M and post-2023 retention change the gap but do not establish a correction.",
        "intent": "trend",
        "question": "Can the public reconstruction reproduce the published DPIRD biomass trajectory?",
        "rationale": "A common annual scale exposes both terminal and historical differences.",
        "comparisonContext": {"baseline": "DPIRD Figure 3.21", "grain": "year", "unit": "B/B0"},
        "type": "line",
        "dataset": "trajectory_comparison",
        "sourceId": "omega-stress-tests",
        "encodings": {
            "x": {"field": "year", "type": "temporal", "label": "Year"},
            "y": {
                "fields": ["published_dpird", "omega_base", "omega_M_0_09", "omega_M_0_13", "omega_post_2023_retention_300"],
                "type": "quantitative",
                "format": "number",
                "label": "Relative female spawning biomass",
                "unit": "B/B0",
            },
            "tooltip": [
                {"field": "published_dpird", "type": "quantitative", "label": "DPIRD"},
                {"field": "omega_base", "type": "quantitative", "label": "Omega baseline"},
            ],
        },
        "yAxisTitle": "Relative female spawning biomass (B/B0)",
        "xAxisTitle": "Year",
        "valueFormat": "number",
        "unit": "B/B0",
        "layout": "full",
        "referenceLines": [
            {"axis": "y", "value": 0.20, "label": "Limit 0.20", "color": "red", "lineStyle": "dashed"},
            {"axis": "y", "value": 0.32, "label": "BMSY 0.32", "color": "orange", "lineStyle": "dotted"},
        ],
        "surface": {"surface": "card", "interactiveLegend": True, "showControls": True, "viewMode": "both"},
    }

    table = {
        "id": "sensitivity-table",
        "title": "Sensitivity and data-removal results",
        "subtitle": "Objectives are not comparable when likelihood weights or included datasets differ.",
        "dataset": "sensitivity",
        "sourceId": "omega-stress-tests",
        "defaultSort": {"field": "absolute_terminal_difference", "direction": "asc"},
        "density": "dense",
        "layout": "full",
        "columns": [
            {"field": "run", "label": "Run", "type": "text"},
            {"field": "terminal_depletion", "label": "Terminal B/B0", "format": "number"},
            {"field": "absolute_terminal_difference", "label": "Absolute gap vs DPIRD", "format": "number"},
            {"field": "trajectory_rmse_vs_digitised_dpird", "label": "Trajectory RMSE", "format": "number"},
            {"field": "terminal_f", "label": "Terminal F", "format": "number"},
            {"field": "objective", "label": "Objective", "format": "number"},
            {"field": "boundary_flags", "label": "Boundary flags", "type": "text"},
            {"field": "note", "label": "Purpose", "type": "text"},
        ],
    }

    summary_text = f"""## What the public test shows

Omega's working public reconstruction ended at **{base['terminal_depletion']:.3f} B/B0**, compared with DPIRD's published **0.150**. The closest tested result was **{low_m['terminal_depletion']:.3f}** under M=0.09, but it still missed the published value and had a worse objective than the M=0.13 run. Selecting M only because it approaches 0.15 would be circular tuning, not a fix.

Removing age compositions moved terminal depletion to **{no_age['terminal_depletion']:.3f}** and pushed parameters to bounds. This means catch and the public CPUE reconstruction do not identify depletion in Omega by themselves; the age information and its weighting are doing most of the work.
"""
    findings_text = f"""## Main findings

1. **No single public parameter change repairs the mismatch.** The tested terminal values ranged from {summary['terminal_depletion'].min():.3f} to {summary['terminal_depletion'].max():.3f}.
2. **The current Omega fit is numerically unstable enough to require stronger multistart/profile work.** Two optimizer seeds differed by {abs(float(base['terminal_depletion']) - float(seed['terminal_depletion'])):.3f} in terminal depletion.
3. **Age composition is the dominant signal in this public reconstruction.** Removing it changed terminal depletion by {abs(float(base['terminal_depletion']) - float(no_age['terminal_depletion'])):.3f} and left the catch/CPUE-only fit on bounds.
4. **Time-varying retention matters.** The illustrative post-2023 L50=300 mm run changed terminal depletion from {base['terminal_depletion']:.3f} to {post_retention['terminal_depletion']:.3f}. Omega now supports annual retention, selectivity, fishing-power and release-mortality overrides, but DPIRD's actual fitted post-2023 values are not public.
5. **The largest scientific gap is recruitment structure.** DPIRD's current model estimates North and South recruitment deviations separately; Omega's present integrated fit does not simultaneously estimate those annual deviations.
"""
    quality_text = """## Evidence quality and limitations

- Exact published biology and model rules are separated from derived conversions and digitised values in `parameter_register.csv`.
- The 2024 catch digitisation is 136.4 t versus the reported 137 t; the digitised Figure 3.21 terminal Brel is 0.149 versus the reported 0.15.
- Catch, CPUE, age compositions and assessment trajectories digitised from figures remain approximate even when those checks agree.
- Raw annual DPIRD input tables, the bespoke ADMB source/run files, accepted SS3 input/output files, fitted selectivity/retention parameters, exact composition weights, and failed/rejected runs were not located in the public releases.
- This is a public-data stress test, not independent certification, an alternative accepted assessment, or evidence that the DPIRD result is wrong.
"""
    request_text = """## Data needed for an exact reproduction

Request these materials from DPIRD before treating an Omega comparison as definitive:

1. Bespoke ADMB `.tpl`, data, parameter, report, covariance, Hessian and gradient files plus run scripts.
2. Accepted SS3 starter, data, control and forecast files, `Report.sso`, `CompReport.sso`, version and executable hash.
3. Annual retained catch and releases by area and sector, with reconstruction method and uncertainty.
4. Standardised CPUE tables with standard errors, record filters, model formulae, vessel/effort effects and fishing-efficiency corrections.
5. Raw age/length counts, sample metadata, ageing-error matrices, effective sample sizes and final weights.
6. Fleet/area/time selectivity and retention parameters, above-legal-size discarding and depth-specific release mortality.
7. Area-specific recruitment deviations, penalties, bias correction, bounds and stock-recruit implementation.
8. Growth time blocks or annual k values, maturity/weight inputs and priors.
9. Objective-function components, likelihood profiles, jitters, retrospectives, sensitivities, convergence diagnostics and rejected runs.
10. Spatial allocation and movement data or the evidence used to assume no movement.
"""
    sources_text = """## Official sources

- [DPIRD 2025 West Coast Demersal Scalefish Resource assessment](https://library.dpird.wa.gov.au/fish_rar/2/)
- [DPIRD FOP 151 external review and response](https://library.dpird.wa.gov.au/fr_fop/101/)
- [DPIRD 2021 assessment (FRR 316)](https://library.dpird.wa.gov.au/fr_rr/133/)
- [DPIRD 2024 resource synopsis (FRR 346)](https://library.dpird.wa.gov.au/fr_rr/264/)

The local source manifest records the exact file hashes used for this report.
"""

    manifest = {
        "version": 1,
        "surface": "report",
        "title": "WA Dhufish public reconstruction — Omega stress-test report",
        "description": "Transparent comparison of official DPIRD public evidence with Omega model stress tests.",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "sources": source_list,
        "cards": cards,
        "charts": [chart],
        "tables": [table],
        "blocks": [
            {"id": "title", "type": "markdown", "body": "# WA Dhufish public reconstruction — Omega stress-test report\n\nA public-evidence benchmark, not a replacement assessment."},
            {"id": "headline", "type": "metric-strip", "cardIds": [card["id"] for card in cards]},
            {"id": "summary", "type": "markdown", "body": summary_text, "sourceId": "omega-stress-tests"},
            {"id": "trajectory", "type": "chart", "chartId": "trajectory-comparison"},
            {"id": "findings", "type": "markdown", "body": findings_text, "sourceId": "omega-stress-tests"},
            {"id": "sensitivity", "type": "table", "tableId": "sensitivity-table"},
            {"id": "quality", "type": "markdown", "body": quality_text, "sourceId": "public-dataset"},
            {"id": "request", "type": "markdown", "body": request_text},
            {"id": "sources", "type": "markdown", "body": sources_text, "sourceId": "dpird-publications"},
        ],
    }
    snapshot = {
        "version": 1,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "status": "partial",
        "datasets": {
            "headline": records(metric_rows),
            "trajectory_comparison": records(comparison),
            "sensitivity": records(summary),
        },
        "accessIssues": [
            {
                "id": "missing-raw-dpird-model-files",
                "scope": "exact assessment reproduction",
                "sourceId": "dpird-publications",
                "message": "Raw DPIRD model inputs, accepted run files and several fitted parameter series were not present in the collected public releases.",
                "actionLabel": "Open official assessment page",
                "actionHref": "https://library.dpird.wa.gov.au/fish_rar/2/",
            }
        ],
    }
    artifact = {
        "surface": "report",
        "manifest": manifest,
        "snapshot": snapshot,
        "sources": source_list,
        "package_info": {"generated_by": "tools/build_dpird_dhufish_report.py"},
    }
    target = REPORT / "artifact.json"
    target.write_text(json.dumps(artifact, indent=2), encoding="utf-8")
    summary.to_csv(REPORT / "stress_test_summary_with_rmse.csv", index=False)
    comparison.to_csv(REPORT / "trajectory_comparison.csv", index=False)
    annual = pd.read_csv(READY / "dpird_wa_dhufish_public_reconstruction.csv")
    parameters = pd.read_csv(READY / "parameter_register.csv")
    workbook_data = {
        "headline": records(metric_rows),
        "sensitivity": records(summary),
        "trajectory": records(comparison),
        "annual_input": records(annual),
        "parameters": records(parameters),
        "sources": sources_manifest["sources"],
        "findings": [
            ["Omega baseline terminal B/B0", float(base["terminal_depletion"])],
            ["DPIRD published terminal B/B0", 0.15],
            ["Closest tested terminal B/B0", float(closest["terminal_depletion"])],
            ["Closest tested variant", str(closest["run"])],
            ["Optimizer seed spread", abs(float(base["terminal_depletion"]) - float(seed["terminal_depletion"]))],
            ["No-age terminal B/B0", float(no_age["terminal_depletion"])],
            ["Post-2023 retention sensitivity terminal B/B0", float(post_retention["terminal_depletion"])],
        ],
        "limitations": [
            "Public reconstruction; not raw DPIRD annual input tables.",
            "Omega currently represents one stock, while DPIRD estimates North and South recruitment separately.",
            "Annual recruitment deviations are not simultaneously estimated in the current Omega integrated fit.",
            "Fitted selectivity, retention, growth-deviation and composition-weight parameters are incomplete in public sources.",
            "Catch, CPUE, age composition and published output series are digitised from official figures and remain approximate.",
        ],
    }
    (REPORT / "workbook_data.json").write_text(json.dumps(workbook_data, indent=2), encoding="utf-8")
    return target


if __name__ == "__main__":
    print(build())
